//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DisofiLafete.MaestrosSoapClient {
    using System.Data;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="MaestrosSoapClient.MaestrosSoap")]
    public interface MaestrosSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ListadoBodega", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet ListadoBodega();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ListadoBodega", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> ListadoBodegaAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ListadoProductos", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet ListadoProductos();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ListadoProductos", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> ListadoProductosAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ListadoUsuarios", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet ListadoUsuarios();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ListadoUsuarios", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> ListadoUsuariosAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ListadoUsuariosNombre", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet ListadoUsuariosNombre(string nombre);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ListadoUsuariosNombre", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> ListadoUsuariosNombreAsync(string nombre);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ListadoLocalesProductos", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet ListadoLocalesProductos();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ListadoLocalesProductos", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> ListadoLocalesProductosAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ListadoProductoPorLocales", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet ListadoProductoPorLocales(string Locales);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ListadoProductoPorLocales", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> ListadoProductoPorLocalesAsync(string Locales);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ListadoClientes", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet ListadoClientes();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ListadoClientes", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> ListadoClientesAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ListadoPorProducto", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet ListadoPorProducto(string productos);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ListadoPorProducto", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> ListadoPorProductoAsync(string productos);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ListadoPorProductoAgrupado", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet ListadoPorProductoAgrupado(string codigoBodega);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ListadoPorProductoAgrupado", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> ListadoPorProductoAgrupadoAsync(string codigoBodega);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface MaestrosSoapChannel : DisofiLafete.MaestrosSoapClient.MaestrosSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class MaestrosSoapClient : System.ServiceModel.ClientBase<DisofiLafete.MaestrosSoapClient.MaestrosSoap>, DisofiLafete.MaestrosSoapClient.MaestrosSoap {
        
        public MaestrosSoapClient() {
        }
        
        public MaestrosSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public MaestrosSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MaestrosSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MaestrosSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Data.DataSet ListadoBodega() {
            return base.Channel.ListadoBodega();
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> ListadoBodegaAsync() {
            return base.Channel.ListadoBodegaAsync();
        }
        
        public System.Data.DataSet ListadoProductos() {
            return base.Channel.ListadoProductos();
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> ListadoProductosAsync() {
            return base.Channel.ListadoProductosAsync();
        }
        
        public System.Data.DataSet ListadoUsuarios() {
            return base.Channel.ListadoUsuarios();
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> ListadoUsuariosAsync() {
            return base.Channel.ListadoUsuariosAsync();
        }
        
        public System.Data.DataSet ListadoUsuariosNombre(string nombre) {
            return base.Channel.ListadoUsuariosNombre(nombre);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> ListadoUsuariosNombreAsync(string nombre) {
            return base.Channel.ListadoUsuariosNombreAsync(nombre);
        }
        
        public System.Data.DataSet ListadoLocalesProductos() {
            return base.Channel.ListadoLocalesProductos();
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> ListadoLocalesProductosAsync() {
            return base.Channel.ListadoLocalesProductosAsync();
        }
        
        public System.Data.DataSet ListadoProductoPorLocales(string Locales) {
            return base.Channel.ListadoProductoPorLocales(Locales);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> ListadoProductoPorLocalesAsync(string Locales) {
            return base.Channel.ListadoProductoPorLocalesAsync(Locales);
        }
        
        public System.Data.DataSet ListadoClientes() {
            return base.Channel.ListadoClientes();
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> ListadoClientesAsync() {
            return base.Channel.ListadoClientesAsync();
        }
        
        public System.Data.DataSet ListadoPorProducto(string productos) {
            return base.Channel.ListadoPorProducto(productos);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> ListadoPorProductoAsync(string productos) {
            return base.Channel.ListadoPorProductoAsync(productos);
        }
        
        public System.Data.DataSet ListadoPorProductoAgrupado(string codigoBodega) {
            return base.Channel.ListadoPorProductoAgrupado(codigoBodega);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> ListadoPorProductoAgrupadoAsync(string codigoBodega) {
            return base.Channel.ListadoPorProductoAgrupadoAsync(codigoBodega);
        }
    }
}
